package:
  name: grass
  version: 7.8.3

source:
  git_url: https://github.com/OSGeo/grass.git
  git_rev: releasebranch_7_8
  patches:
    - platform.make.in.patch [osx]
    - platform.make.in-linux.patch [linux]
    - loader.py.patch
    - rules.make.patch [osx]
    - rules.make.patch [linux]
    - aclocal.m4.patch
    - configure.patch
    - install.make.patch
    - module.make.patch [osx]
    - shlib.make.patch [osx]

requirements:
  build:
    - clang_osx-64 [osx]
    - clangxx_osx-64 [osx]
    - gcc_linux-64 [linux]
    - gxx_linux-64 [linux]
    - mesalib
    - libglu [linux]
    - python
    - setuptools
    - numpy
    - gdal
    - freetype
    - cairo
    - matplotlib
    - pandoc
    - wxpython
    - sqlite
    - jpeg
    - libpng
    - libtiff
    - pkg-config [osx]
    - libiconv
    - fftw
    - blas
    - giflib
    - python.app [osx]
    - poppler
    - proj
    - geos
    - krb5
    - flex
    - bison

  run:
    - libgcc
    - python
    - setuptools
    - numpy
    - gdal
    - freetype
    - cairo
    - matplotlib
    - pandoc
    - wxpython
    - sqlite
    - jpeg
    - libpng
    - libtiff
    - pkg-config [osx]
    - libiconv
    - fftw
    - blas
    - giflib
    - python.app [osx]
    - proj
    - geos
    - krb5

build:
  number: 0

about:
  summary: Geographic Resources Analysis Support System
  description: |
    GRASS GIS, commonly referred to as GRASS (Geographic Resources
    Analysis Support System), is a free and open source Geographic
    Information System (GIS) software suite used for geospatial data
    management and analysis, image processing, graphics and maps
    production, spatial modeling, and visualization.
  home: https://grass.osgeo.org/
  license: GPLv2
  dev_url: https://grass.osgeo.org/development/
