{% set name = "grass" %}
{% set version = "7.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://grass.osgeo.org/grass72/source/grass-7.2.0.tar.gz

requirements:
  build:
    - python
    - setuptools
    - numpy
    - gdal
    - freetype
    - cairo
    - matplotlib
    - pandoc
    - pil
    - wxpython
    - sqlite
    - fftw
    - jpeg
    - libpng
    - libtiff
    - blas
    - giflib
    - pkg-config [osx]

  run:
    - python
    - setuptools
    - numpy
    - gdal
    - freetype
    - cairo
    - matplotlib
    - pandoc
    - pil
    - wxpython
    - sqlite
    - fftw
    - jpeg
    - libpng
    - libtiff
    - blas
    - giflib
    - pkg-config [osx]

build:
  number: 0
