language: generic
os:
# - linux
- osx
osx_image: xcode6.4
env:
  global:
  - PREFIX=$HOME/grass
  - MACOSX_DEPLOYMENT_TARGET="10.9"
  - TRAVIS_PYTHON_VERSION="2.7"
  - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda2-latest"
sudo: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
- bash $HOME/minconda.sh -b -p $PREFIX
- export PATH="$PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda install $TRAVIS_PYTHON_VERSION
- conda install -q conda-build anaconda-client
- conda list
- conda info -a
script:
- travis_wait 40 conda build ./recipe -c noaa-orr-erd -c conda-forge --old-build-string
after_success:
- curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py
  > $HOME/anaconda_upload.py
- echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack --old-build-string --token=-
