name: CI

on:
- push
- pull_request

jobs:
  build:

    name: Test build - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-18.04
        - macos-10.15
    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: 3.7
    - name: Configure environment
      shell: bash -l {0}
      run: |
        conda config --set always_yes yes
        conda install -q conda-build
        conda config --add channels conda-forge
        conda config --add channels csdms-stack
        conda install make
    - name: Build
      run: |
        conda build recipe/ --python=3.7
